############################
## CHANGE THESE
############################

baseURL: "https://yoshiouchi.github.io/"
title: "Yoshi | Solutions Engineer"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
