############################
## CHANGE THESE
############################

baseURL: "https://yoshiouchi.github.io/yoshiouchi.github.io"
title: yoshiouchi.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
