############################
## Author
############################

author:
  name: "Yoshi"
  image: author.jpeg
  greeting: "Solutions Engineer @ GitHub 🇯🇵🇦🇺"
  icon: "👋"

############################
## Links
############################

links:
  - github: https://github.com/yoshiouchi
  - linkedin: https://www.linkedin.com/in/yoshiouchi

###############################
## OpenGraph & Twitter Cards
###############################

title: "Yoshi | Solutions Engineer"
description: "Personal portfolio and blog of Yoshi — Solutions Engineer at GitHub"
images:
  - thumbnail.jpeg